### ISSUE TITLE
Expressions spanning multiple lines lack context

### ISSUE THREAD

**Issue by moodmosaic** [CoinFabrik/stacy#21]
Steps to reproduce:

```
git clone https://github.com/Trust-Machines/BNS-V2.git
cd BNS-V2
git checkout 97be5fd93e7676f74bfca5aecdbd84008e52e474
stacy-analyzer lint contracts/BNS-V2.clar > output.txt
grep -A 2 -B 2 ' 1225 |' output.txt

Warning: Use of tx-sender inside an assert
      |
 1225 |         (asserts!
      |          ^^^^^^^^
      Note: Consider using contract-caller.
```

Perhaps it would be best to print some context, e.g. 2 lines before/after the current line?

---

The expression can be found also [here](https://github.com/Trust-Machines/BNS-V2/blob/97be5fd93e7676f74bfca5aecdbd84008e52e474/contracts/BNS-V2.clar#L1225-L1232):

```clar
(asserts! 
    (match namespace-manager 
        manager 
        (is-eq contract-caller manager)
        (is-eq tx-sender (get namespace-import namespace-props))
    ) 
    ERR-NOT-AUTHORIZED
)
```

**Comment by moodmosaic** [comment]
We noticed this with @BowTiedRadone in https://github.com/Trust-Machines/BNS-V2/issues/70#issuecomment-2236031501.

**Comment by faculerena** [comment]
I teied maybe in cases like this showing all the lines until the parenthesis are balanced, but that lead to really long messages in cases where the function signature is highlighted ( the entire function is printed).
Showing only 2 lines above and below could be a good compromise. 

What do you thing about shorter messages behind a flag for cases when it's wanted?

**Comment by moodmosaic** [comment]
Perhaps the default would be the current behavior, and when needed a flag could expand context to Ν lines.

**Comment by faculerena** [comment]
Hey @moodmosaic, @BowTiedRadone. I added this just now. Hope it's working as you intended. After trying it in a few contracts with formatting similar as the ones you sent, I think it's really useful!

**Comment by moodmosaic** [comment]
Thank you!
